definitions:
  handler.CreateOpportunityRequest:
    properties:
      company:
        type: string
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
    type: object
  handler.CreateOpportunityResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.OpportunityResponse'
      message:
        type: string
      status:
        type: integer
    type: object
  handler.EditOpportunityResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.OpportunityResponse'
      message:
        type: string
      status:
        type: integer
    type: object
  handler.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: integer
    type: object
  handler.ListOpportunityResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/schemas.OpportunityResponse'
        type: array
      message:
        type: string
      status:
        type: integer
    type: object
  handler.RemoveOpportunityResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.OpportunityResponse'
      message:
        type: string
      status:
        type: integer
    type: object
  handler.ShowOpportunityResponse:
    properties:
      data:
        $ref: '#/definitions/schemas.OpportunityResponse'
      message:
        type: string
      status:
        type: integer
    type: object
  handler.UpdateOpportunityRequest:
    properties:
      company:
        type: string
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
    type: object
  schemas.OpportunityResponse:
    properties:
      company:
        type: string
      created_at:
        type: string
      delete_at:
        type: string
      id:
        type: integer
      link:
        type: string
      location:
        type: string
      remote:
        type: boolean
      role:
        type: string
      salary:
        type: integer
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /opportunities:
    get:
      consumes:
      - application/json
      description: List opportunities
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ListOpportunityResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: List opportunities
      tags:
      - opportunities
    post:
      consumes:
      - application/json
      description: Create an opportunity
      parameters:
      - description: Opportunity object
        in: body
        name: opportunity
        required: true
        schema:
          $ref: '#/definitions/handler.CreateOpportunityRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.CreateOpportunityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Create an opportunity
      tags:
      - opportunities
  /opportunities/{id}:
    delete:
      consumes:
      - application/json
      description: Remove an opportunity
      parameters:
      - description: Opportunity ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.RemoveOpportunityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Remove an opportunity
      tags:
      - opportunities
    get:
      consumes:
      - application/json
      description: Show an opportunity
      parameters:
      - description: Opportunity ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.ShowOpportunityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Show an opportunity
      tags:
      - opportunities
    put:
      consumes:
      - application/json
      description: Edit an opportunity
      parameters:
      - description: Opportunity ID
        in: path
        name: id
        required: true
        type: string
      - description: Opportunity object
        in: body
        name: opportunity
        required: true
        schema:
          $ref: '#/definitions/handler.UpdateOpportunityRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.EditOpportunityResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Edit an opportunity
      tags:
      - opportunities
swagger: "2.0"
